# Generated by Django 5.2.6 on 2025-09-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_bids',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10),
        ),
    ]
